---
- name: add Docker APT key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: lifecycle == "install"

- name: add Docker APT repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: "kubernetes"
  when: lifecycle == "install"

- name: remove Docker APT repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: absent
    filename: "kubernetes"
  when: lifecycle == "remove"

- name: remove Docker APT key
  become: yes
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent
  when: lifecycle == "remove"